version: "3.9"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: auth_db
    ports:
      -   "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./init-scripts:/docker-entrypoint-initdb.d
volumes:
  pgdata:
